### PR TITLE
Create subsite

### PR DESCRIPTION
**Pull request by doofusdavid**
##### Summary

Add "Subsite Of" site type to site creation and update.  This adds another parameter to site create/update called "subsiteof."

##### Additional Information

First: I've been using Wordops to host production sites for three years now, with the majority being multisite networks consisting of > 40 sites per install.  Around 500 domains total.  This is my first code contribution to WordOps, and while this is something I can use immediately, please feel free to reject or suggest changes because this functionality will literally make my life easier on a near-daily basis.

The rationale for this change is as follows:

For large multisite wpsubdir networks, Wordpress allows you to rename the subsites to be completely different domains.  These subsite domains should have their own logging, SSL and nginx configuration, however they use the same webroot as their "parent" site.  

Example:

```
# Create multisite and add two subsites
wo site create multisite.local --wpsubdir
wo site create a.local --subsiteof multisite.local
wo site create b.local --subsiteof multisite.local

# create single site, realize mistake, and convert to subsite
wo site create singlesite.local --wp
wo site update singlesite.local --subsiteof multisite.local

```

This is addressing: https://community.wordops.net/d/1004-current-best-approach-to-wp-multisite-with-mapped-domains-tlds

Also, it may help address:
https://github.com/WordOps/WordOps/issues/106

### CODE REVIEW

**Comment by VirtuBox** [comment]
Hello @doofusdavid,
Many thanks for this great contribution. I'm going to test it and to merge it as soon as possible.

**Comment by doofusdavid** [comment]
Test lots please!!  Half of my time was getting down how the project was laid out and how to build/test!

**Comment by doofusdavid** [comment]
Fixed an issue found in testing in https://github.com/WordOps/WordOps/pull/598/commits/401be08fe95f82786541c9b485b2edff3b029b8a

**Comment by VirtuBox** [comment]
> Test lots please!! Half of my time was getting down how the project was laid out and how to build/test!

I apologize about that. If you are able to list what is missing in our documentation or just to write some tips to work on a new feature for WordOps, I will take the time to add it properly to docs.wordops.net. 
Many thanks for your work. I have enabled automated CI in this pull request so you should be able to test easily your code.

**Comment by VirtuBox** [comment]
@doofusdavid don't worry about Codacy Static Code Analysis CI, I will fix it after merging your PR.

**Comment by doofusdavid** [comment]
> I apologize about that. If you are able to list what is missing in our documentation or just to write some tips to work on a new feature for WordOps, I will take the time to add it properly to docs.wordops.net. Many thanks for your work. I have enabled automated CI in this pull request so you should be able to test easily your code.

No need to apologize, I run into this whenever running something I didn't create.  For what it's worth, I didn't find (also didn't look super hard) for instructions for developers.  I think the CONTRIBUTING.md file just has a stub for developers.  I'm happy to write up any additional documentation (I love WordOps...seriously) if you can confirm I'm doing things properly.

My workflow right now is VSCode ssh-ed to an ubuntu VM.  I make changes on my development machine, then go over to the ubuntu machine and do sudo python3 setup.py build && sudo python3 setup.py install.  Then I can try some things out.  I never figured out a way to actually debug the code, so if there was a way to do that locally, it would save a lot of time going forward, because I'd still like to help as much as possible.

**Comment by VirtuBox** [comment]
Hello @doofusdavid,
I'm going to merge your pull request and to run some tests before publishing a new release.
Thanks again for your contribution. I will also take the time to write a developer documentation and I hope you will be able to tell me if there are some missing informations.

**Comment by dutuka** [comment]
Hello,
i want to create a multisite network  using subdomain and subdir: 
wo site create subdomain.domain.com --wpsubdir

and then i want to add subsite to this network like this: subdomain.domain.com/subsite1

After setup subsite1, i want to clone subsite1 to subsite2:
subdomain.domain.com/subsite1 --> subdomain.domain.com/subsite2

Is it possible to do this using Create subsite feature? Thanks

**Comment by doofusdavid** [comment]
Hey there, thanks for using this; I'm glad it's helpful! I do believe that the subsite can be added that way. However, the ability to clone a subsite to another one is outside the scope of this function, as it involves creating a new site ID, creating the uploads folder for that site, copying all content from subsite1 to subsite2, and updating all URLs on subsite2 to point to the new location. Cloning would be a cool new feature.

Currently, we use this plugin, which, while out of date, has continued to work for us, but there are a lot of other options: https://wordpress.org/plugins/multisite-clone-duplicator/

**Comment by dutuka** [comment]
Thank you for your response,  to optimize performance and reduce compatiblity issue with updates i want to avoid using plugins as much as possible, if there is a solution to clone subsites on server level with wordops I would prefer to use that. I hope you can implement cloning feature in the future, ecspecially with the possibility to specify the blogID of the new clone subsite with an argument, something like: 
wo site clone subdomain.domain.com/subsite1 --> subdomain.domain.com/subsite2 --newBlogID=<number>
This would be really a cool feature.

**Pull request merged**
