### PR TITLE
added null check on user

### PR DESCRIPTION
**Pull request by tareqsifat**
##### Summary
 Added null check on user so that user will be initiated as WordOps when installing with --silent flag if linux $USER in empty like in docker in my case

### Original Code

```bash
if [ "$wo_force_install" = "y" ]; then
    [ ! -f "$HOME/.gitconfig" ] && {
        bash -c 'echo -e "[user]\n\tname = $USER\n\temail = root@$HOSTNAME.local" > $HOME/.gitconfig';
    }
fi

```

### Updated Code
```bash
Copy code
if [ "$wo_force_install" = "y" ]; then
    # Check if USER is empty and assign to a fallback variable
    USER_OR_WORDOPS=${USER:-WordOps}

    [ ! -f "$HOME/.gitconfig" ] && {
        bash -c "echo -e \"[user]\n\tname = $USER_OR_WORDOPS\n\temail = root@$HOSTNAME.local\" > $HOME/.gitconfig";
    }
fi
```
### Story
Last Thursday, I encountered an issue installing WordOps in a Docker container using the `--silent` flag. The installation process failed because the `$USER` variable was not set properly in the Docker environment. This caused the `.gitconfig`  user set to null so that NGINX setup failed with the error `Unable to git commit at /etc/nginx `

To resolve this, I modified the installation script to handle scenarios where `$USER` is empty by introducing a fallback value (`WordOps`). This ensures the `.gitconfig` file is always generated with a valid user name, regardless of the environment.

##### Additional Information

- Changes
Introduced a Fallback Variable: If $USER is empty, the fallback variable USER_OR_WORDOPS is set to WordOps.
Improved Compatibility: This fix ensures the script works seamlessly in Docker environments and other contexts where $USER might not be defined.
- Benefits
Fixes Installation Failures: Ensures WordOps installation does not fail due to missing $USER in Docker containers.
Increases Robustness: Makes the installation script more resilient and versatile.
Enhances Developer Experience: Provides a reliable setup process in diverse environments, saving time and avoiding errors.

### CODE REVIEW

**Comment by VirtuBox** [comment]
Thanks for your contribution and for this well explained pull request @tareqsifat.

**Comment by agplanner** [comment]
Hey! All good? Could you tell me or tell me what configuration you made to use Wordops with Docker? I would be grateful @tareqsifat

**Comment by Ethical-Cronos** [comment]
Hey! All good? Could you tell me or tell me what configuration you made to use Wordops with Docker? I would be grateful @tareqsifat

**Comment by tareqsifat** [comment]
Hlw @Ethical-Cronos 
### here is my docker file

`FROM debian:bullseye-slim`

 Prevent interactive prompts during package installation
`ENV DEBIAN_FRONTEND=noninteractive`

Set the USER environment variable
`ENV USER=root`

 Install dependencies required for WordOps
`RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    wget \
    jq \
    lsb-release \
    ca-certificates \
    gnupg \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*`

`
RUN wget -qO wo wops.cc && sudo bash wo --silent \
    && wo stack install --php74 --nginx --wpcli && wo site create local.ilhum.com --php74 --wp --vhostonly`

**Pull request merged**
